### Obtener todos
GET http://localhost:8002/aan_node/all
Accept: application/json

### Obtener uno
GET http://localhost:15002/aan_node/one
Accept: application/json
Content-Type: application/json

{
  "node_id": "node1"
}

### Obtener trace
GET http://localhost:15002/aan_node/trace
Accept: application/json
Content-Type: application/json

{
  "node_id": "node1"
}